Allcases support for enums
nodes-vapor/sourcery-templates pull request #16
Opened 2017-10-06 08:19 UTC by BrettRToomey

2017-10-26 11:49 UTC, BrettRToomey commented
Fixes #25

2017-11-06 05:32 UTC, steffendsommer requested changes

2017-11-06 05:32 UTC, steffendsommer commented on README.md
> +TODO
Let's get these filled in as well. Also I think we might have to clean up some old enum annotations in the readme.

2017-11-06 05:32 UTC, steffendsommer commented on README.md
> +TODO
The controller section with how routes are being generated seems a bit outdated as well

2017-11-15 12:05 UTC, steffendsommer approved these changes

2017-11-15 12:05 UTC, merged